apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: redis-prom-rule
  namespace: monitoring
  labels:
    prometheus: k8s
    role: alert-rules
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
spec:
  groups:
  - name: redis-prom-rule
    rules:
    - alert: RedisDown
      expr: up{job="redis"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "REDIS está fora do ar"
        description: "O nosso servidor REDIS está fora do ar"
