apiVersion: apps/v1
kind: Deployment
metadata:
  name: giropops-senhas-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: giropops-senhas
  template:
    metadata:
      labels:
        app: giropops-senhas
    spec:
      containers:
      - name: giropops-senhas
        image: juanozorio/giropops-senhas:1.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "0.5"
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: redis
