apiVersion: apps/v1
kind: Deployment
metadata:
  name: giropops-senhas-app
spec:
  selector:
    matchLabels:
      app: giropops-senhas
  template:
    metadata:
      labels:
        app: giropops-senhas
    spec:
      containers:
      - name: giropops-senhas
        image: juanozorio/giropops-senhas:1.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
          requests:
            memory: "256Mi"
            cpu: "0.3"
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: redis
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 20
          timeoutSeconds: 5