apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: cgr.dev/chainguard/redis:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "0.2"
        ports:
        - containerPort: 6379

      - name: redis-exporter
        image: oliver006/redis_exporter:v1.29.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "0.2"
        ports:
        - containerPort: 9121
        env:
        - name: REDIS_ADDR
          value: redis
