apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    name: tcp-redis
  - protocol: TCP
    port: 9121
    targetPort: 9121
    name: tcp-redis-exporter
  type: ClusterIP
