name: Docker Image CI

on:
  push:
    paths:
      - '**.py'
      - 'Dockerfile'

jobs:
  build-scan-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Run Kubelinter
        uses: stackrox/kube-linter-action@v1
        with:
          config: "./config/kubelinter/kubelinter.yaml"
          directory: "./manifests"

      - name: Build Docker Image
        run: docker build -t juanozorio/giropops-senhas:1.0 .

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@0.16.1
        with:
          image-ref: "juanozorio/giropops-senhas:1.0"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.3.0

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.USERNAME_DOCKER }}
          password: ${{ secrets.PASSWORD_DOCKER }}

      - name: Docker Push
        run: docker push juanozorio/giropops-senhas:1.0

      - name: Get Image Digest
        id: get_digest
        run: echo "::set-output name=digest::$(docker image inspect juanozorio/giropops-senhas:1.0 --format='{{index .RepoDigests 0}}')"

      - name: Set up Cosign Secrets
        run: echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key

      - name: Sign Docker Image
        run: cosign sign --yes --key cosign.key ${{ steps.get_digest.outputs.digest }}
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
