name: Docker Image

on:
  push:
    paths:
      - "**.py"
      - "Dockerfile"

jobs:
  build-image:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.3.0

      - name: Build Docker Image
        run: docker build -t ${{ vars.DOCKER_TAG }} .

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@0.16.1
        with:
          image-ref: "${{ vars.DOCKER_TAG }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.USERNAME_DOCKER }}
          password: ${{ secrets.PASSWORD_DOCKER }}

      - name: Docker Push
        run: docker push ${{ vars.DOCKER_TAG }}

      - name: Set up Cosign Secrets
        run: echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key

      - name: Sign Docker Image
        run: cosign sign --yes --key cosign.key ${{ vars.DOCKER_TAG }}
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}